name: .NET Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 6 * * *

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./CurrencyConverter
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./CurrencyConverter
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./CurrencyConverter
